### ISSUE TITLE
genotype_to_string and genotype_to_text failure

### ISSUE THREAD

**Issue by phantomas1234** [biosustain/gnomic#12]
from gnomic.utils import genotype_to_string, genotype_to_text

	from gnomic import Mutation, FeatureTree, Feature, Accession

	g = Mutation(new=FeatureTree(Feature(type='reaction', accession=Accession(identifier='3OAR140'), variant='down-regulation(-0.996)')), old=FeatureTree(Feature(type='reaction', accession=Accession(identifier='3OAR140'))), multiple=False)
	genotype_to_text(g)

fails with

	---------------------------------------------------------------------------
	AttributeError                            Traceback (most recent call last)
	<ipython-input-33-db861f18a11d> in <module>()
	      4 
	      5 g = Mutation(new=FeatureTree(Feature(type='reaction', accession=Accession(identifier='3OAR140'), variant='down-regulation(-0.996)')), old=FeatureTree(Feature(type='reaction', accession=Accession(identifier='3OAR140'))), multiple=False)
	----> 6 genotype_to_text(g)

	/Users/niso/anaconda3/lib/python3.5/site-packages/gnomic/utils.py in genotype_to_text(genotype, fusions)
	     24     """
	     25     parts = []
	---> 26     for change in genotype.changes(fusions=fusions):
	     27         parts.append(change_to_text(change))
	     28 

	AttributeError: 'Mutation' object has no attribute 'changes'

**Comment by phantomas1234** [comment]
sorry, that doesn't work because the input is actually not a `Genotype`

**Comment by lyschoening** [comment]
@phantomas1234 a `Mutation` is not a genotype, but a change. You want to use `change_to_text()` not `genotype_to_text()`

**Comment by lyschoening** [comment]
Haha, the button changed to Reopen just as I clicked :)

**Comment by phantomas1234** [comment]
from gnomic.utils import genotype_to_string, genotype_to_text, change_to_text, change_to_string

	from gnomic import Mutation, FeatureTree, Feature, Accession

	g = Mutation(new=FeatureTree(Feature(type='reaction', accession=Accession(identifier='3OAR140'), variant='down-regulation(-0.996)')), old=FeatureTree(Feature(type='reaction', accession=Accession(identifier='3OAR140'))), multiple=False)
	change_to_string(g)

That one seems to be broken too?

	AttributeError                            Traceback (most recent call last)
	<ipython-input-43-561e8086745e> in <module>()
	      4 
	      5 g = Mutation(new=FeatureTree(Feature(type='reaction', accession=Accession(identifier='3OAR140'), variant='down-regulation(-0.996)')), old=FeatureTree(Feature(type='reaction', accession=Accession(identifier='3OAR140'))), multiple=False)
	----> 6 change_to_string(g)

	/Users/niso/anaconda3/lib/python3.5/site-packages/gnomic/utils.py in change_to_string(change)
	    118                 s = '{}>>{}'.format(feature_to_string(change.old), feature_to_string(change.new))
	    119             else:
	--> 120                 s = '{}>{}'.format(feature_to_string(change.old), feature_to_string(change.new))
	    121         elif change.old is None:
	    122             # FIXME phenotypes should not have a + or - prefix; only a postfix.

	/Users/niso/anaconda3/lib/python3.5/site-packages/gnomic/utils.py in feature_to_string(feature)
	    146         return ':'.join(feature_to_string(f) for f in feature.contents)
	    147     elif isinstance(feature, FeatureTree):
	--> 148         contents = ' '.join(feature_to_string(f) for f in feature.contents)
	    149         if isinstance(feature, FeatureSet):
	    150             return '{{{contents}}}'.format(contents=contents)

	/Users/niso/anaconda3/lib/python3.5/site-packages/gnomic/utils.py in <genexpr>(.0)
	    146         return ':'.join(feature_to_string(f) for f in feature.contents)
	    147     elif isinstance(feature, FeatureTree):
	--> 148         contents = ' '.join(feature_to_string(f) for f in feature.contents)
	    149         if isinstance(feature, FeatureSet):
	    150             return '{{{contents}}}'.format(contents=contents)

	/Users/niso/anaconda3/lib/python3.5/site-packages/gnomic/utils.py in feature_to_string(feature)
	    146         return ':'.join(feature_to_string(f) for f in feature.contents)
	    147     elif isinstance(feature, FeatureTree):
	--> 148         contents = ' '.join(feature_to_string(f) for f in feature.contents)
	    149         if isinstance(feature, FeatureSet):
	    150             return '{{{contents}}}'.format(contents=contents)

	/Users/niso/anaconda3/lib/python3.5/site-packages/gnomic/utils.py in <genexpr>(.0)
	    146         return ':'.join(feature_to_string(f) for f in feature.contents)
	    147     elif isinstance(feature, FeatureTree):
	--> 148         contents = ' '.join(feature_to_string(f) for f in feature.contents)
	    149         if isinstance(feature, FeatureSet):
	    150             return '{{{contents}}}'.format(contents=contents)

	/Users/niso/anaconda3/lib/python3.5/site-packages/gnomic/utils.py in feature_to_string(feature)
	    155     else:
	    156         s = ''
	--> 157         if feature.type and feature.type.name != 'phene':
	    158             s += '{}.'.format(feature.type.name)
	    159 

	AttributeError: 'str' object has no attribute 'name'

**Comment by lyschoening** [comment]
Feature.type must be a `Type`.
