### ISSUE TITLE
Single nucleotide deletion not working

### ISSUE THREAD

**Issue by lyschoening** [biosustain/gnomic#27]
The following should be valid: `c.123del`

http://varnomen.hgvs.org/recommendations/DNA/variant/deletion/

via @meono

**Comment by Melanie-M** [comment]
@meono @lyschoening
`g = Genotype.parse('+gene(c.123del)')` works for me in both master and version-1.

There's also a test case `c.1234del` that passes.

**Comment by lyschoening** [comment]
Turns out it was just unreleased. Released v0.7.0
